// Generated by CoffeeScript 1.6.2
(function() {
  var DENSITIES, KNOWN_INGREDIENTS, ML_PER_CUP, k, knownDensities, parseFraction,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  DENSITIES = {
    "all-purpose flour": 0.528,
    "brown sugar": 0.93,
    "butter": 0.959,
    "chopped walnuts or pecans": 0.461,
    "granulated sugar": 0.849,
    "semisweet chocolate chips": 0.725
  };

  (typeof exports !== "undefined" && exports !== null ? exports : window).massimize = function(recipe) {
    return recipe.replace(KNOWN_INGREDIENTS, function(match, amount, unit, ingredient) {
      var g, mL;

      mL = parseFraction(amount) * (/cup/.test(unit) ? ML_PER_CUP : 1);
      g = mL * DENSITIES[ingredient];
      return "" + (g.toFixed()) + "g " + ingredient;
    });
  };

  ML_PER_CUP = 236.588;

  knownDensities = ((function() {
    var _results;

    _results = [];
    for (k in DENSITIES) {
      _results.push(k.replace(/\s+/g, "\\s+"));
    }
    return _results;
  })()).join("|");

  KNOWN_INGREDIENTS = RegExp("((?:[0-9]+\\s+)?[0-9]+(?:/[0-9]+)?)\\s+(cups?|mL)\\s+(" + knownDensities + ")", "g");

  parseFraction = function(fraction) {
    var decimal, denominator, numerator, part, _i, _len, _ref, _ref1;

    decimal = 0;
    _ref = fraction.split(/\s+/);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      part = _ref[_i];
      if (__indexOf.call(part, "/") >= 0) {
        _ref1 = part.split("/"), numerator = _ref1[0], denominator = _ref1[1];
        decimal += parseInt(numerator, 10) / parseInt(denominator, 10);
      } else {
        decimal += parseInt(part, 10);
      }
    }
    return decimal;
  };

}).call(this);
